version: '3'

services:
  monitoring:
    image: ghcr.io/eclipse-slm/slm-monitoring-prometheus-aas:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"

  prometheus:
    image: ghcr.io/eclipse-slm/monitoring-prometheus:v2.43.0
    networks:
      default:
        aliases:
          - prometheus
    ports:
      - "9090:9090"
