### Application
application:
  name: "^project.artifactId^"
  version: "^project.version^"
  timestamp: "^timestamp^"

### Deployment
deployment:
  scheme: "http"
  hostname: "localhost"
  port: ${server.port}
  path: "/monitoring/aas"
  url: ${deployment.scheme}://${deployment.hostname}:${deployment.port}${deployment.path}

### Server / API
server:
  port: 9080
  error:
    include-message: always
  servlet:
    context-path: ${deployment.path}
  forward-headers-strategy: framework

### Spring
spring:
  application:
    name: monitoring_aas
  cloud:
    consul:
      host: ${consul.host}
      port: ${consul.port}
      discovery:
        enabled: true
        hostname: ${consul.service.address}
        port: ${consul.service.port}
        acl-token: ${consul.acl-token}
        register-health-check: true
        healthCheckPath: ${deployment.path}/actuator/health
        tags:
          - slm
          - backend
          - monitoring
          - ${spring.application.name}
          - exposed
          - traefik.http.routers.monitoring-aas.rule=PathPrefix(`${deployment.path}`)
        service-name: ${consul.service.name}
        instance-id: ${consul.service.name}
        metadata:
          version: ${application.version}

management:
  endpoints:
    web.exposure.include: health,info
  info:
    git.enabled: false

### Consul
consul:
  service:
    name: monitoring-aas
    address: host.docker.internal
    port: ${server.port}
  scheme: http
  host: localhost
  port: 8500
  datacenter: fabos
  acl-token: bEHRXzvTnWaK1lTf50NGZBeM

### Prometheus
prometheus:
  host: "localhost"
  port: 9090
